import Foundation

// MARK: - MonthlyReportEngine

/// Pure builder for the "Export last month" markdown report surfaced from
/// Reports. Everything is derived from a single `AppData` snapshot plus an
/// injectable `now`/`calendar` so the output is deterministic and testable
/// in isolation — no side effects, no I/O. The view layer is responsible
/// for handing the resulting string to a file exporter.
enum MonthlyReportEngine {

    /// A calendar-month window expressed both as components (for labelling)
    /// and as ISO "yyyy-MM-dd" string bounds. The bounds are half-open
    /// `[startStr, endStr)` so they can be compared directly against the
    /// fixed-width ISO date strings stored on check-ins and completions.
    struct MonthRange: Equatable, Sendable {
        let year: Int
        let month: Int
        let label: String     // e.g. "May 2026"
        let startStr: String  // inclusive  — first day of the month
        let endStr: String    // exclusive — first day of the following month
    }

    private static let monthLabelFormatter: DateFormatter = {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.dateFormat = "MMMM yyyy"
        return f
    }()

    /// The last *complete* calendar month relative to `now`. On 2026-06-13
    /// this returns May 2026 (`2026-05-01` ..< `2026-06-01`).
    static func lastCompleteMonth(now: Date = Date(), calendar: Calendar = .current) -> MonthRange? {
        let thisMonthComps = calendar.dateComponents([.year, .month], from: now)
        guard let startOfThisMonth = calendar.date(from: thisMonthComps),
              let startOfLastMonth = calendar.date(byAdding: .month, value: -1, to: startOfThisMonth) else {
            return nil
        }
        let comps = calendar.dateComponents([.year, .month], from: startOfLastMonth)
        guard let year = comps.year, let month = comps.month else { return nil }
        return MonthRange(
            year: year,
            month: month,
            label: monthLabelFormatter.string(from: startOfLastMonth),
            startStr: DateFormatting.dateString(startOfLastMonth),
            endStr: DateFormatting.dateString(startOfThisMonth)
        )
    }

    /// Build the full markdown report for `month` from the data snapshot.
    /// `now` is used only for the point-in-time sections (stagnation signals
    /// and habit streaks, which have no historical record to slice by month).
    static func markdown(
        from data: AppData,
        month: MonthRange,
        now: Date = Date(),
        calendar: Calendar = .current
    ) -> String {
        var lines: [String] = []
        lines.append("# Monthly Review — \(month.label)")
        lines.append("")
        lines.append("_Generated by MortalLoom. All data stays on your device._")
        lines.append("")

        let apex = data.goals.activeApex
        if let apex {
            lines.append("**North Star:** \(apex.title)")
            lines.append("")
        }

        lines.append(contentsOf: alignmentSection(apex: apex, month: month))
        lines.append(contentsOf: reflectionSection(apex: apex, month: month))
        lines.append(contentsOf: stagnationSection(data: data, now: now))
        lines.append(contentsOf: habitSection(data: data, now: now, calendar: calendar))

        return lines.joined(separator: "\n")
    }

    // MARK: - Sections

    /// Average reflection rating across the month plus the first→last delta,
    /// off the apex's reflection check-ins. Mirrors the Reports alignment
    /// trend, scoped to a single month.
    private static func alignmentSection(apex: Goal?, month: MonthRange) -> [String] {
        var out = ["## Alignment trend", ""]
        let ratings: [(date: String, rating: Int)] = (apex?.checkIns ?? [])
            .compactMap { c in
                guard let r = c.alignmentRating,
                      c.date >= month.startStr, c.date < month.endStr else { return nil }
                return (c.date, r)
            }
            .sorted { $0.date < $1.date }

        guard !ratings.isEmpty else {
            out.append("No alignment reflections recorded this month.")
            out.append("")
            return out
        }

        let avg = Double(ratings.reduce(0) { $0 + $1.rating }) / Double(ratings.count)
        out.append(String(format: "- Average alignment: **%.1f / 10** (%@) across %d reflection%@",
                          avg,
                          AlignmentScale.label(for: Int(avg.rounded())),
                          ratings.count,
                          ratings.count == 1 ? "" : "s"))
        if let first = ratings.first, let last = ratings.last, ratings.count >= 2 {
            let delta = last.rating - first.rating
            let sign = delta >= 0 ? "+" : ""
            out.append("- Trend: \(first.rating) → \(last.rating) (\(sign)\(delta) over the month)")
        }
        out.append("")
        return out
    }

    /// Reflection excerpts: every apex check-in in the month that carries a
    /// written note or reflection content, rendered newest-first.
    private static func reflectionSection(apex: Goal?, month: MonthRange) -> [String] {
        var out = ["## Reflections", ""]
        let entries = (apex?.checkIns ?? [])
            .filter { c in
                c.date >= month.startStr && c.date < month.endStr
                    && (c.isReflection || !c.note.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
            }
            .sorted { $0.date > $1.date }

        guard !entries.isEmpty else {
            out.append("No reflections recorded this month.")
            out.append("")
            return out
        }

        for c in entries {
            var header = "### \(DateFormatting.displayDate(c.date))"
            if let rating = c.alignmentRating {
                header += " — alignment \(rating)/10"
            }
            out.append(header)
            if let prompt = c.promptAnswered, !prompt.isEmpty {
                out.append("> \(prompt)")
            }
            let note = c.note.trimmingCharacters(in: .whitespacesAndNewlines)
            if !note.isEmpty {
                out.append(note)
            }
            if !c.commitments.isEmpty {
                out.append("")
                out.append("Commitments:")
                for commitment in c.commitments {
                    out.append("- \(commitment)")
                }
            }
            out.append("")
        }
        return out
    }

    /// Current stagnation signals. These are computed from present state and
    /// carry no history, so the section is explicitly labelled "as of" today
    /// rather than pretending to be a month-scoped snapshot.
    private static func stagnationSection(data: AppData, now: Date) -> [String] {
        var out = ["## What's stalling (as of \(DateFormatting.dateString(now)))", ""]
        let signals = StagnationEngine.signals(goals: data.goals, habits: data.habits, now: now)
        guard !signals.isEmpty else {
            out.append("Nothing is stalling right now.")
            out.append("")
            return out
        }
        for s in signals {
            out.append("- **\(s.title)** — \(s.detail)")
        }
        out.append("")
        return out
    }

    /// Current habit streak + 30-day hit-rate summary. Like stagnation
    /// signals these are point-in-time, computed as of `now`.
    private static func habitSection(data: AppData, now: Date, calendar: Calendar) -> [String] {
        var out = ["## Habit streaks", ""]
        let active = data.habits.filter { $0.isActive }
        guard !active.isEmpty else {
            out.append("No active habits.")
            out.append("")
            return out
        }
        for h in active {
            let streak = HabitEngine.currentStreak(h, now: now, calendar: calendar)
            let hitRate = HabitEngine.targetHitRate(h, windowDays: 30, now: now, calendar: calendar)
            out.append(String(format: "- **%@** — %d-period streak, %d%% 30-day hit rate",
                              h.name, streak, Int(hitRate.rounded())))
        }
        out.append("")
        return out
    }
}
